#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jun 30, 2018 01:53:11 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import QC_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Quest_Calculator (root)
    QC_support.init(root, top)
    root.mainloop()

w = None
def create_Quest_Calculator(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Quest_Calculator (w)
    QC_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Quest_Calculator():
    global w
    w.destroy()
    w = None


class Quest_Calculator:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'
        font11 = "-family Terminal -size 18 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font13 = "-family Terminal -size 12 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        font14 = "-family {Segoe UI} -size 9 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1280x720")
        top.title("Quest Calculator")
        top.configure(background="#000000")
        top.configure(cursor="arrow")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame = Frame(top)
        self.Frame.place(x=5, y=8, height=704, width=1264)
        self.Frame.configure(borderwidth="8")
        self.Frame.configure(background="#202020")
        self.Frame.configure(highlightbackground="#d9d9d9")
        self.Frame.configure(highlightcolor="black")

        self.B_Skills = Button(self.Frame)
        self.B_Skills.place(x=765, y=8,  height=48, width=240)
        self.B_Skills.configure(activebackground="#f9f9f9")
        self.B_Skills.configure(activeforeground="black")
        self.B_Skills.configure(background="#c020f8")
        self.B_Skills.configure(borderwidth="4")
        self.B_Skills.configure(cursor="hand2")
        self.B_Skills.configure(disabledforeground="#a3a3a3")
        self.B_Skills.configure(font=font11)
        self.B_Skills.configure(foreground="#ffa0ff")
        self.B_Skills.configure(highlightbackground="#d9d9d9")
        self.B_Skills.configure(highlightcolor="black")
        self.B_Skills.configure(overrelief="flat")
        self.B_Skills.configure(pady="0")
        self.B_Skills.configure(takefocus="0")
        self.B_Skills.configure(text='''SKILLS''')

        self.B_Entities = Button(self.Frame)
        self.B_Entities.place(x=5, y=8,  height=48, width=248)
        self.B_Entities.configure(activebackground="#f9f9f9")
        self.B_Entities.configure(activeforeground="black")
        self.B_Entities.configure(background="#00a0f8")
        self.B_Entities.configure(borderwidth="4")
        self.B_Entities.configure(cursor="hand2")
        self.B_Entities.configure(disabledforeground="#a3a3a3")
        self.B_Entities.configure(font=font11)
        self.B_Entities.configure(foreground="#a0e0f8")
        self.B_Entities.configure(highlightbackground="#d9d9d9")
        self.B_Entities.configure(highlightcolor="black")
        self.B_Entities.configure(pady="0")
        self.B_Entities.configure(takefocus="0")
        self.B_Entities.configure(text='''ENTITIES''')

        self.B_Items = Button(self.Frame)
        self.B_Items.place(x=260, y=8,  height=48, width=248)
        self.B_Items.configure(activebackground="#f9f9f9")
        self.B_Items.configure(activeforeground="black")
        self.B_Items.configure(background="#f8e000")
        self.B_Items.configure(borderwidth="4")
        self.B_Items.configure(cursor="hand2")
        self.B_Items.configure(disabledforeground="#a3a3a3")
        self.B_Items.configure(font=font11)
        self.B_Items.configure(foreground="#ffff60")
        self.B_Items.configure(highlightbackground="#d9d9d9")
        self.B_Items.configure(highlightcolor="black")
        self.B_Items.configure(overrelief="flat")
        self.B_Items.configure(pady="0")
        self.B_Items.configure(takefocus="0")
        self.B_Items.configure(text='''ITEMS''')

        self.B_Battle = Button(self.Frame)
        self.B_Battle.place(x=520, y=8,  height=48, width=240)
        self.B_Battle.configure(activebackground="#f9f9f9")
        self.B_Battle.configure(activeforeground="black")
        self.B_Battle.configure(background="#f83800")
        self.B_Battle.configure(borderwidth="4")
        self.B_Battle.configure(cursor="hand2")
        self.B_Battle.configure(disabledforeground="#a3a3a3")
        self.B_Battle.configure(font=font11)
        self.B_Battle.configure(foreground="#ffa080")
        self.B_Battle.configure(highlightbackground="#d9d9d9")
        self.B_Battle.configure(highlightcolor="black")
        self.B_Battle.configure(overrelief="flat")
        self.B_Battle.configure(pady="0")
        self.B_Battle.configure(takefocus="0")
        self.B_Battle.configure(text='''BATTLE''')

        self.B_Effects = Button(self.Frame)
        self.B_Effects.place(x=1015, y=8,  height=48, width=240)
        self.B_Effects.configure(activebackground="#f9f9f9")
        self.B_Effects.configure(activeforeground="black")
        self.B_Effects.configure(background="#00e020")
        self.B_Effects.configure(borderwidth="4")
        self.B_Effects.configure(cursor="hand2")
        self.B_Effects.configure(disabledforeground="#a3a3a3")
        self.B_Effects.configure(font=font11)
        self.B_Effects.configure(foreground="#80ff80")
        self.B_Effects.configure(highlightbackground="#d9d9d9")
        self.B_Effects.configure(highlightcolor="black")
        self.B_Effects.configure(overrelief="flat")
        self.B_Effects.configure(pady="0")
        self.B_Effects.configure(takefocus="0")
        self.B_Effects.configure(text='''EFFECTS''')

        self.Listbox1 = Listbox(self.Frame)
        self.Listbox1.place(x=630, y=192, height=328, width=132)
        self.Listbox1.configure(background="#000000")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font=font14)
        self.Listbox1.configure(foreground="#000000")
        self.Listbox1.configure(highlightbackground="#101010")
        self.Listbox1.configure(highlightcolor="#181818")
        self.Listbox1.configure(highlightthickness="5")
        self.Listbox1.configure(relief=FLAT)
        self.Listbox1.configure(selectbackground="#181818")
        self.Listbox1.configure(selectborderwidth="5")
        self.Listbox1.configure(selectforeground="black")
        self.Listbox1.configure(selectmode=MULTIPLE)
        self.Listbox1.configure(takefocus="0")
        self.Listbox1.configure(width=128)

        self.EntityFrame = Frame(self.Frame)
        self.EntityFrame.place(x=5, y=64, height=632, width=1248)
        self.EntityFrame.configure(borderwidth="1")
        self.EntityFrame.configure(background="#2040a0")
        self.EntityFrame.configure(highlightbackground="#102080")
        self.EntityFrame.configure(highlightcolor="black")
        self.EntityFrame.configure(highlightthickness="8")
        self.EntityFrame.configure(width=1253)

        self.Listbox1_1 = Listbox(self.EntityFrame)
        self.Listbox1_1.place(x=15, y=16, height=368, width=156)
        self.Listbox1_1.configure(background="#001040")
        self.Listbox1_1.configure(disabledforeground="#a3a3a3")
        self.Listbox1_1.configure(font=font14)
        self.Listbox1_1.configure(foreground="#000000")
        self.Listbox1_1.configure(highlightbackground="#102080")
        self.Listbox1_1.configure(highlightcolor="#181818")
        self.Listbox1_1.configure(highlightthickness="5")
        self.Listbox1_1.configure(relief=FLAT)
        self.Listbox1_1.configure(selectbackground="#181818")
        self.Listbox1_1.configure(selectborderwidth="5")
        self.Listbox1_1.configure(selectforeground="black")
        self.Listbox1_1.configure(selectmode=MULTIPLE)
        self.Listbox1_1.configure(takefocus="0")
        self.Listbox1_1.configure(width=156)

        self.Level = Label(self.EntityFrame)
        self.Level.place(x=180, y=16,  height=32, width=96)
        self.Level.configure(activebackground="#f9f9f9")
        self.Level.configure(activeforeground="black")
        self.Level.configure(anchor=W)
        self.Level.configure(background="#2040a0")
        self.Level.configure(disabledforeground="#a3a3a3")
        self.Level.configure(font=font13)
        self.Level.configure(foreground="#c0e0ff")
        self.Level.configure(highlightbackground="#2060c0")
        self.Level.configure(highlightcolor="black")
        self.Level.configure(text='''Level 1''')

        self.XP = Label(self.EntityFrame)
        self.XP.place(x=180, y=40,  height=32, width=32)
        self.XP.configure(activebackground="#f9f9f9")
        self.XP.configure(activeforeground="black")
        self.XP.configure(anchor=W)
        self.XP.configure(background="#2040a0")
        self.XP.configure(disabledforeground="#a3a3a3")
        self.XP.configure(font=font13)
        self.XP.configure(foreground="#c0e0ff")
        self.XP.configure(highlightbackground="#2060c0")
        self.XP.configure(highlightcolor="black")
        self.XP.configure(text='''XP''')

        self.HP = Label(self.EntityFrame)
        self.HP.place(x=180, y=64,  height=32, width=32)
        self.HP.configure(activebackground="#f9f9f9")
        self.HP.configure(activeforeground="black")
        self.HP.configure(anchor=W)
        self.HP.configure(background="#2040a0")
        self.HP.configure(disabledforeground="#a3a3a3")
        self.HP.configure(font=font13)
        self.HP.configure(foreground="#c0e0ff")
        self.HP.configure(highlightbackground="#2060c0")
        self.HP.configure(highlightcolor="black")
        self.HP.configure(text='''HP''')

        self.XP_bar = ttk.Progressbar(self.EntityFrame)
        self.XP_bar.place(x=220, y=48, width=128, height=16)
        #self.XP_bar.configure(activebackground="#0f30f0")
        self.XP_bar.configure(takefocus="0")
        self.XP_bar.configure(value=50)


        self.fra38_lis40 = Listbox(self.Frame)
        self.fra38_lis40.place(x=0, y=0, height=1, width=1)
        self.fra38_lis40.configure(background="#000000")
        self.fra38_lis40.configure(disabledforeground="#a3a3a3")
        self.fra38_lis40.configure(font=font14)
        self.fra38_lis40.configure(foreground="#000000")
        self.fra38_lis40.configure(highlightbackground="#101010")
        self.fra38_lis40.configure(highlightcolor="#181818")
        self.fra38_lis40.configure(highlightthickness="5")
        self.fra38_lis40.configure(relief=FLAT)
        self.fra38_lis40.configure(selectbackground="#181818")
        self.fra38_lis40.configure(selectborderwidth="5")
        self.fra38_lis40.configure(selectforeground="black")
        self.fra38_lis40.configure(selectmode=MULTIPLE)
        self.fra38_lis40.configure(takefocus="0")
        self.fra38_lis40.configure(width=128)

        self.fra38_lis41 = Listbox(self.Frame)
        self.fra38_lis41.place(x=0, y=0, height=1, width=1)
        self.fra38_lis41.configure(background="#000000")
        self.fra38_lis41.configure(disabledforeground="#a3a3a3")
        self.fra38_lis41.configure(font=font14)
        self.fra38_lis41.configure(foreground="#000000")
        self.fra38_lis41.configure(highlightbackground="#101010")
        self.fra38_lis41.configure(highlightcolor="#181818")
        self.fra38_lis41.configure(highlightthickness="5")
        self.fra38_lis41.configure(relief=FLAT)
        self.fra38_lis41.configure(selectbackground="#181818")
        self.fra38_lis41.configure(selectborderwidth="5")
        self.fra38_lis41.configure(selectforeground="black")
        self.fra38_lis41.configure(selectmode=MULTIPLE)
        self.fra38_lis41.configure(takefocus="0")
        self.fra38_lis41.configure(width=128)


if __name__ == '__main__':
    vp_start_gui()
